name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/arm64/v8
          - linux/amd64
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Pull
        run: git pull origin master
      - name: Install Dependencies
        run: |
          sudo apt install -y make build-essential libjansson-dev libyder-dev liborcania-dev libulfius-dev
      - name: Compile Project
        run: make
      - name: Run tests
        run: make tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
